### ISSUE TITLE
CANNOT GET TO WORK! INSTALL ERROR + FREEZE!

### ISSUE THREAD

**Issue by XMVZ** [MainSilent/hCaptcha-Bypass#4]
hi!

thank you so much for sharing this!
can't seem to get it to work. at first was having an error with install, but then found the code was deprecated, so implemented the below:

import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')

now when i run your code i am receiving a freeze error:

\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

amongst many other lines...

please help!

**Comment by XMVZ** [comment]
Also

ERROR: Could not find a version that satisfies the requirement seleniumwire (from versions: none)

**Comment by MainSilent** [comment]
I have added a requirements file, The code still works but the `captcha_token.py` didn't work for me, You need to set the cookie directly and get the `hc_accessibility` token and hard code it in `main.py` line 31

**Comment by XMVZ** [comment]
Ok so just to be clear, do NOT use the captcha_token.py file? Just use the main.py file and put the token into it? Isn't the token what we're trying to get here?

**Comment by XMVZ** [comment]
So what exactly is the script doing at that point?

**Comment by XMVZ** [comment]
Also do you have Discord or Telegram - I have a question for you about implementing POSTing the cookie to an API...

**Comment by XMVZ** [comment]
Btw, I ran captcha_token.py and got this in my browser:

{"error":"not-found"}

**Comment by MainSilent** [comment]
I meant the `hc_accessibility` token, This is the token that when you check the box it doesn't show you the dialog and let you to proceed without solving the captcha, This script uses that to generate new tokens for a site key to send requests

**Comment by XMVZ** [comment]
When I run captcha_token.py it returns the accessibility token for me... Maybe I'm wrong, but the console is printing the cookie...

**Comment by XMVZ** [comment]
Unless I'm looking at something else... I really just want to know how to then have this cookie POSTed to an API so it can be GET.

**Comment by MainSilent** [comment]
If you have that cookie now you can run main.py to generate a token and use that in the API to send request, Are you using that for discord?

**Comment by MainSilent** [comment]
This issue has been closed due to inactivity
