### ISSUE TITLE
Cant get hcaptcha key

### ISSUE THREAD

**Issue by adv-zl** [MainSilent/hCaptcha-Bypass#5]
When I start main.py it hangs on 'Waiting for key...'. I checked developers console and saw:

![image](https://user-images.githubusercontent.com/16443377/150517558-9aef80d9-26c2-4e8b-a532-63f56932ae70.png)

**Comment by adv-zl** [comment]
Where I need to get this? I dont undestand: "Get captcha key from Hcaptcha accessibility copy the button link"

On discord.com?

**Comment by MainSilent** [comment]
If you are trying to get tokens for discord the settings by default are set for that, Currently the cookie script is deprecated, You need to get `hc_accessbility` token by signing up in `https://dashboard.hcaptcha.com/signup?type=accessibility` and click on `Set Cookie` button, After that copy the `hc_accessbility` cookie value and hard code it in main.py line 31

**Comment by MainSilent** [comment]
This issue has been closed due to inactivity
